package com.adamly.xin6.dao;

import com.adamly.xin6.dataobject.GoodsStockDO;
import org.apache.ibatis.annotations.Param;

public interface GoodsStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Wed Oct 23 15:50:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Wed Oct 23 15:50:42 CST 2019
     */
    int insert(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Wed Oct 23 15:50:42 CST 2019
     */
    int insertSelective(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Wed Oct 23 15:50:42 CST 2019
     */
    GoodsStockDO selectByPrimaryKey(Integer id);
    GoodsStockDO selectByGoodsId(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Wed Oct 23 15:50:42 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Wed Oct 23 15:50:42 CST 2019
     */
    int updateByPrimaryKey(GoodsStockDO record);
    int decreaseStock(@Param("goodsId") Integer goodsId, @Param("amount") Integer amount);
}