package com.adamly.xin6.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class PromoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.id
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.name
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.start_date
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    private Date startDate;

    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.promo_goods_price
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    private BigDecimal promoGoodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.goods_id
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.id
     *
     * @return the value of promo_info.id
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.id
     *
     * @param id the value for promo_info.id
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.name
     *
     * @return the value of promo_info.name
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.name
     *
     * @param name the value for promo_info.name
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.start_date
     *
     * @return the value of promo_info.start_date
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.start_date
     *
     * @param startDate the value for promo_info.start_date
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.promo_goods_price
     *
     * @return the value of promo_info.promo_goods_price
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    public BigDecimal getPromoGoodsPrice() {
        return promoGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.promo_goods_price
     *
     * @param promoGoodsPrice the value for promo_info.promo_goods_price
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    public void setPromoGoodsPrice(BigDecimal promoGoodsPrice) {
        this.promoGoodsPrice = promoGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.goods_id
     *
     * @return the value of promo_info.goods_id
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.goods_id
     *
     * @param goodsId the value for promo_info.goods_id
     *
     * @mbg.generated Sun Oct 27 16:19:57 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}